flowchart TD
  %% Symbol legend:
  %%   [FC] = Fixed-cost
  %%   [IH] = Inventory holding
  %%   [LHL] = Labour hour limit
  %%   [MATE] = Material
  %%   [OL] = Overtime labour
  %%   [RL] = Regular labour
  %%   [SHOR] = Shortage
  A1[Production planning]
  A1 --> B2[Entities]
  B2 --> C3[Periods]
  C3 --> D4[Multi-period]
  D4 --> E5["T = {t}"]
  B2 --> C6[Products]
  C6 --> D7[Single-product]
  C6 --> D8[Multi-product]
  D8 --> E9["P = {p}"]
  A1 --> B10[Parameters]
  B10 --> C11["[IH] Initial inventory"]
  C11 --> D12[I_0]
  C11 --> D13["I_{0,p}"]
  B10 --> C14[Cost]
  C14 --> D15[Unit production cost]
  D15 --> E16[labour]
  E16 --> F17["[RL] Regular time workers"]
  F17 --> G18[c_t]
  F17 --> G19["c_{t,p}"]
  E16 --> F20["[OL] Over time workers"]
  F20 --> G21[o_t]
  F20 --> G22["o_{t,p}"]
  D15 --> E23["[MATE] unit material cost"]
  E23 --> F24[m_t]
  E23 --> F25["m_{t,p}"]
  C14 --> D26["[IH] Unit holding cost"]
  D26 --> E27[h_t]
  D26 --> E28["h_{t,p}"]
  C14 --> D29["[FC] Set-up cost"]
  D29 --> E30[s_t]
  D29 --> E31["s_{t,p}"]
  C14 --> D32["[SHOR] Shortage cost"]
  D32 --> E33[g_t]
  D32 --> E34["g_{t,p}"]
  B10 --> C35[Demand]
  C35 --> D36[d_t]
  C35 --> D37["d_{t,p}"]
  B10 --> C38["[LHL] Labour hour required"]
  C38 --> D39[h_t]
  C38 --> D40["h_{t,p}"]
  B10 --> C41[Limitations]
  C41 --> D42["[LHL] Labour hour limit"]
  D42 --> E43[UB^L_t]
  D42 --> E44["UB^L_{t,p}"]
  C41 --> D45["[MATE] Material budget limit"]
  D45 --> E46[UB^P_t]
  D45 --> E47["UB^M_{t,p}"]
  A1 --> B48[Decision]
  B48 --> C49[How many to produce]
  C49 --> D50["[RL] by regular hour labour"]
  D50 --> E51[x_t]
  D50 --> E52["x_{t,p}"]
  C49 --> D53["[OL] by over time labour"]
  D53 --> E54[y_t]
  D53 --> E55["y_{t,p}"]
  B48 --> C56["[IH] Inventory to hold"]
  C56 --> D57[z_t]
  C56 --> D58["z_{t,p}"]
  B48 --> C59["[FC] To produce or not"]
  C59 --> D60[u_t]
  C59 --> D61["u_{t,p}"]
  B48 --> C62["[SHOR] Shortage"]
  C62 --> D63[v_t]
  C62 --> D64["v_{t,p}"]
  A1 --> B65[Objective function]
  B65 --> C66["[RL] Total regular hour labour cost"]
  C66 --> D67["\\sum_t c_tx_t"]
  C66 --> D68["\\sum_t \\sum_p c_{t,p} x_{t,p}"]
  B65 --> C69["[OL] Total over time labour cost"]
  C69 --> D70["\\sum_t o_t y_t"]
  C69 --> D71["\\sum_t \\sum_p o_{t,p} y_{t,p}"]
  B65 --> C72["[IH] Total holding cost"]
  C72 --> D73["\\sum_t h_t z_t"]
  C72 --> D74["\\sum_t \\sum_p h_{t,p} z_{t,p}"]
  B65 --> C75["[FC] Total set-up cost"]
  C75 --> D76["\\sum_t s_t u_t"]
  C75 --> D77["\\sum_t \\sum_p s_{t,p} u_{t,p}"]
  B65 --> C78["[SHOR] Total shortage cost"]
  C78 --> D79["\\sum_t g_t v_t"]
  C78 --> D80["\\sum_t \\sum_p g_{t,p} v_{t,p}"]
  B65 --> C81["[MATE] Total material cost"]
  C81 --> D82["\\sum_t m_t x_t"]
  C81 --> D83["\\sum_{t,p} m_{t,p} x_{t,p}"]
  A1 --> B84[Constraints]
  B84 --> C85[Explicit constraints]
  C85 --> D86[Demand of production]
  D86 --> E87[for each t]
  E87 --> F88["[SHOR] v_t"]
  F88 --> G89["[RL] + x_t"]
  G89 --> H90["[OL] + y_t"]
  H90 --> I91["[IH] u_{t-1} - u_t"]
  I91 --> J92[at least]
  J92 --> K93["\\leq"]
  I91 --> J94[exactly]
  J94 --> K95[=]
  I91 --> J96[at most]
  J96 --> K97["\\geq"]
  D86 --> E98[for each t, for each p]
  E98 --> F99["[SHOR] v_{t,p}"]
  F99 --> G100["[RL] + x_{t,p}"]
  G100 --> H101["[OL] + y_{t,p}"]
  H101 --> I102["[IH] u_{t-1,p} - u_{t,p}"]
  I102 --> J103[at least]
  J103 --> K104["\\leq"]
  I102 --> J105[exactly]
  J105 --> K106[=]
  I102 --> J107[at most]
  J107 --> K108["\\geq"]
  C85 --> D109["[IH] Inventory balance"]
  D109 --> E110[for each t]
  E110 --> F111["[RL] [IH] u_t = u_{t-1} + x_t - d_t"]
  F111 --> G112["[OL] + y_t"]
  G112 --> H113["[SHOR] - v_t"]
  D109 --> E114[for each t, for each p]
  E114 --> F115["[RL] [IH] u_{t,p} = u_{t-1,p} + x_{t,p} - d_{t,p}"]
  F115 --> G116["[OL] + y_{t,p}"]
  G116 --> H117["[SHOR] - v_{t,p}"]
  C85 --> D118["[LHL] Labour hour limit"]
  D118 --> E119[for each t]
  E119 --> F120["UB^L_t \\geq h_t x_t"]
  F120 --> G121[+ h_t y_t]
  D118 --> E122[for each t, for each p]
  E122 --> F123["UB^L_{t,p} \\geq h_{t,p} x_{t,p}"]
  F123 --> G124["+ h_t y_{t,p}"]
  C85 --> D125["[MATE] Material budget limit"]
  D125 --> E126[for each t]
  E126 --> F127["UB^M_t \\geq m_t x_t"]
  F127 --> G128[+ m_t y_t]
  D125 --> E129[for each t, for each p]
  E129 --> F130["UB^M_{t,p} \\geq m_{t,p} x_{t,p}"]
  F130 --> G131["+ m_{t,p} y_{t,p}"]
  B84 --> C132[Implicit constraints]
  C132 --> D133["[FC] Production is possible only if set-up is #quot;true#quot;"]
  D133 --> E134[for each t]
  E134 --> F135["[IH] y_t"]
  F135 --> G136["[RL] [FC] + x_t \\leq D_t u_t"]
  D133 --> E137[for each t, for each p]
  E137 --> F138["[IH] y_{t,p}"]
  F138 --> G139["[RL] [FC] + x_{t,p} \\leq D_{t,p} u_{t,p}"]